{{- $fullname := include "clickhouse.fullname" $ }}
{{- $labels := include "clickhouse.labels" $ }}
{{- with $.Values.clickhouse.backup }}
{{- if .enabled }}

{{- if .config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-backup-config
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: clickhouse-backup
data:
  config.yml: |
    {{- .config | nindent 4 }}
{{- end }}

{{- if not .cronjob.script.existingConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-backup-initiator
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: clickhouse-backup
data:
  backup.sh: |
{{- if .cronjob.script.content }}
  {{- .cronjob.script.content | nindent 4 }}
{{- else }}
  {{- $.Files.Get "sources/backup.sh" | nindent 4 }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
