{{- if and (not .Values.clickhouse.backup.config.existingSecret) .Values.clickhouse.backup.config.content }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" $ }}-backup-config
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
type: Opaque
data:
  config.yml: {{ .Values.clickhouse.backup.config.content | b64enc }}
{{- end }}
