{{- if and .Values.clickhouse.distributedQuerySecret.enabled .Values.clickhouse.distributedQuerySecret.createSecret }}
{{- $secret := .Values.clickhouse.distributedQuerySecret.secret }}
{{- if $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.distributedQuerySecretName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
type: Opaque
data:
  secret: {{ $secret | b64enc }}
{{- else }}
{{- fail "Secret must be provided when distributedQuerySecret is enabled and createSecret is true" }}
{{- end }}
{{- end }}